### ISSUE TITLE
struts2-json-plugin-2.3.16.jar!/struts-plugin.xml; lineNumber: 6; columnNumber: 20; Element type "struts" must be declared.

### ISSUE THREAD

**Issue by jeetendra29gupta** [cenobites/struts2-json-plugin#3]
Caused by: Element type "struts" must be declared. - jar:file:/home/jeetendragupta/Eclipse/workspace/Official/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GUI/WEB-INF/lib/struts2-json-plugin-2.3.16.jar!/struts-plugin.xml:6:20
	at com.opensymphony.xwork2.util.DomHelper.parse(DomHelper.java:115)
	at com.opensymphony.xwork2.config.providers.XmlConfigurationProvider.loadConfigurationFiles(XmlConfigurationProvider.java:885)
	... 27 more
Caused by: org.xml.sax.SAXParseException; systemId: jar:file:/home/jeetendragupta/Eclipse/workspace/Official/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GUI/WEB-INF/lib/struts2-json-plugin-2.3.16.jar!/struts-plugin.xml; lineNumber: 6; columnNumber: 20; Element type "struts" must be declared.

**Comment by nycholas** [comment]
Hi,

Please, put more information about this issue (like an example).

Thank you.
